name: Generate WikiPathways RDF

on:
  workflow_dispatch:

jobs:
  changed-gpmls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # check this out repository
        uses: actions/checkout@v4

      - name: Checkout repository
        # checkout the GPMLs
        uses: actions/checkout@v4
        with:
          repository: wikipathways/wikipathways-database
          path: database
          fetch-depth: 0
          ref: main

      - name: Cache GPML2RDF with dependencies
        uses: actions/cache@v3
        id: cacheMetaJar
        with:
          path: ./gpml2rdf-4.0.2.jar
          key: cached-gpmlrdf-action-${{ hashFiles('gpml2rdf-4.0.2.jar') }}
          restore-keys: |
            cached-gpmlrdf-action-${{ hashFiles('gpml2rdf-4.0.2.jar') }}
            cached-gpmlrdf-action-

      - if: steps.cacheMetaJar.outputs.cache-hit != 'true'
        name: Install deps
        run: |
          echo "Cache not found: gpml2rdf-4.0.2.jar"
          if [ ! -e ./gpml2rdf-4.0.2.jar ]; then
            wget -O gpml2rdf-4.0.2.jar https://github.com/egonw/org.pathvisio.io.rdf/releases/download/4.0.2/gpml2rdf-4.0.2.jar
          fi

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Count the number of pathways
        run: |
          mkdir -p rdf
          for f in `find database -name "*\.gpml" | grep -v pending | sort`; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "generating info and datanode files for $wpid"
            mkdir -p rdf/${wpid}
            java -cp gpml2rdf-4.0.2.jar org.wikipathways.wp2rdf.CreateRDF $f rdf/${wpid}/${wpid}.gpml.ttl rdf/${wpid}/${wpid}.wp.ttl || true
          done

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add count.txt
          git add rdf
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Updated RDF'
              git pull --rebase
              git push
          fi
